### ISSUE TITLE
Security token contract 

### ISSUE THREAD

**Issue by vaibhavchellani** [merkaliser/scilla-vanilla#16]
Security token contract needs to be added as it might be of use to a lot of users

**Comment by iamjaspreetsingh** [comment]
ERC-1400: Security Token Standard can be implemented.
Referring https://github.com/ethereum/EIPs/issues/1400

**Comment by vaibhavchellani** [comment]
awesome

**Comment by iamjaspreetsingh** [comment]
in #26, i am getting issues regarding how do i use structure in scilla, so trying to implement the same with mapping. So, functions related to tranches are incomplete. Other functions are done.
