### ISSUE TITLE
Implement Faucet Contract

### ISSUE THREAD

**Issue by merkaliser** [merkaliser/scilla-vanilla#30]
Having a faucet contract to assist people who want to distribute tokens for testing should be very useful and should find a place in the repo .

**Comment by merkaliser** [comment]
@abhishektanwar would you be willing to work on this ? There should be various samples available already .

**Comment by merkaliser** [comment]
Since @abhishektanwar is working on refundable crowdsale at the moment , @iamjaspreetsingh can you look into this ?

**Comment by iamjaspreetsingh** [comment]
Sure, I will look into it
