### ISSUE TITLE
Write tests for erc223 

### ISSUE THREAD

**Issue by merkaliser** [merkaliser/scilla-vanilla#38]
We need to write tests for erc223 . 
For each transition you are testing, you can use the blockchain.json, state.json and input.json to generate the output.json
Here is an example : https://github.com/Zilliqa/kaya/tree/master/test

**Comment by AmritKumar** [comment]
@merkaliser If the goal is testing, why don't you use `scilla-runner` instead? You can build `scilla-runner` from the Scilla repo: https://github.com/Zilliqa/scilla. Kaya is kind of an overkill here.

**Comment by vaibhavchellani** [comment]
thanks @AmritKumar for your input ! moving onto scilla-runner now , was avoiding building scilla-runner wanted to use remote one ;)

**Comment by vaibhavchellani** [comment]
fixed by #39
