### ISSUE TITLE
math contract more functions

### ISSUE THREAD

**Issue by iamjaspreetsingh** [merkaliser/scilla-vanilla#9]
A few more transitions like max, min and average needs to be added in maths contract. 

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/Math.sol

**Comment by vaibhavchellani** [comment]
@iamjaspreetsingh can we close this or are there more functions to be made ?

**Comment by iamjaspreetsingh** [comment]
@vaibhavchellani the functions are completed but I am getting doubt in one of the function i.e. Average.
In reference to
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/Math.sol#L18

I need to use the formula (a / 2) + (b / 2) + ((a % 2 + b % 2) / 2) to avoid overflow. Using this generates a runtime error. 
I can't use mod function directly.
Can it be the reason?
(At present for mod I replace and calculate it by divide, multiply and subtract.)

**Comment by vaibhavchellani** [comment]
as per suggestions from gitter group , we should remove integer operations as those can be handled safely by scilla , we should however implement functions like average , GCD , LCD etc as a library like [this](https://github.com/Zilliqa/scilla/tree/master/src/stdlib) .
